### ISSUE TITLE
Tried emitting when not connected

### ISSUE THREAD

**Issue by Mudasir441** [Krishna21Soni13/socket-chat#1]
I am running this code on simulator but it shows tableview empty after setting name in popup. Here is the log:

LOG SocketIOClient{/}: Handling event: statusChange with data: [connecting, 2]
 LOG SocketIOClient{/}: Joining namespace /
 LOG SocketManager: Tried connecting socket when engine isn't open. Connecting
 LOG SocketManager: Adding engine
 LOG SocketEngine: Starting engine. Server: http://192.168.1.43:3001
 LOG SocketEngine: Handshaking
 LOG SocketEnginePolling: Doing polling GET http://192.168.1.43:3001/socket.io/?transport=polling&b64=1
 LOG SocketIOClient{/}: Handling event: error with data: ["Tried emitting when not connected"]
 LOG SocketIOClient{/}: Adding handler for event: userList

**Comment by nikhil191090** [comment]
@Mudasir441 i also getting this type of error i see you closed the issue , did you find any solution
